spring:
  application:
    name: spring-boot-keycloak-integration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PowerRanger
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  docker:
    compose:
      lifecycle-management: start_only
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: springboot-keycloak
      principle-attribute: preferred_username
